### ISSUE TITLE
원문 출처 문의

### ISSUE THREAD

**Issue by nattybear** [RedBe-an/haskell-korea#1]
안녕하세요.

하스켈 한국어 자료를 만들어 주셔서 감사합니다.

번역에 기여를 하고 싶습니다. 어떤 자료를 번역 중이신지 알 수 있을까요?

**Comment by RedBe-an** [comment]
제가 배너에 글을 잘못 달아놓은 거 같습니다...

번역이 아니라 처음부터 문서를 만드는 작업을 하는 중이였으며, 

만약 기여를 해주실 의향이 있으시다면 알고 계신 지식으로 문서를 생성하시면 됩니다.

문의해주셔서 감사합니다.
